/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jddevaughnbrown' at '11/13/17 12:53 PM' with Gradle 2.14.1
 *
 * @author jddevaughnbrown, @date 11/13/17 12:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
